#!/usr/bin/env python3

import sys
import os
import json
from tkinter import Tk, Canvas, BOTH
sys.path.append(os.path.abspath('../Fish/Common'))
sys.path.append(os.path.abspath('../Fish'))

from Admin.referee import Referee, make_referee_same_fish
from Player.player import PlayerAI

if __name__ == '__main__':
    game_description = json.load(sys.stdin)
    row = game_description['row']
    col = game_description['column']
    players_json = game_description['players']
    fish_per_tile = game_description['fish']

    id_to_player = {}
    player_ai_list = []
    for i in range(0, len(players_json)):
        cur_player = PlayerAI(i, depth=players_json[i][1])
        id_to_player[cur_player.id] = players_json[i][0]
        player_ai_list.append(cur_player)
    
    ref = make_referee_same_fish(player_ai_list, row, col, fish_per_tile)
 
    winner_ids = ref.run_game()
    winner_names = [id_to_player[player_id] for player_id in winner_ids]
    winner_names.sort()
    print(json.dumps(winner_names))

